# Generated by Django 3.2.9 on 2022-05-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('west', '0002_auto_20220513_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Handbags', 'Handbags'), ('Footwear', 'Footwear'), ('Jewelery', 'Jewelery'), ('Tshirts', 'Tshirts'), ('Watches', 'Watches'), ('Shades', 'Shades')], max_length=30),
        ),
    ]
