# Generated by Django 3.2.9 on 2022-05-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('west', '0004_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.CharField(default='user', max_length=30),
            preserve_default=False,
        ),
    ]
